version: '3.9'

services:
  container_mysql-admin-db:
    image: mysql:8.0
    container_name: container_mysql-admin-db
    environment:
      MYSQL_HOST: container_mysql-admin-db
      MYSQL_DATABASE: adminapp-db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_PORT: 3306

    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER --password=$MYSQL_PASSWORD

  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-admindb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: container_mysql-admin-db
      PMA_USER: root
      PMA_PASSWORD:
    depends_on:
      - container_mysql-admin-db
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
